### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by alex-shamshurin** [oliverfindl/vue-svg-inline-loader#19]
1. Config added to vue.config.js

```
  chainWebpack: config => {
    config.resolve.modules.add(appSrc);

    config.module
      .rule('vue')
      .use('vue-svg-inline-loader')
      .loader('vue-svg-inline-loader')
      .options({
        inline: {
          strict: false,
        },
      });

    config.resolve.alias.set(
      'ui.css',
      pathResolve(appSrc, 'constants', 'ui.css'),
    );

    /* Вставка версии */
    config.plugin('define').tap(definitions => {
      // eslint-disable-next-line no-param-reassign
      definitions[0] = Object.assign(definitions[0], {
        __VERSION__: JSON.stringify(appPackageJson.version),
      });
      return definitions;
    });

   const eslintRule = config.module.rule('eslint');
    eslintRule.uses.clear();

    config
      .plugin('NormalModuleReplacementPlugin')
      .use(webpack.NormalModuleReplacementPlugin, [
        /element-ui[/\\]lib[/\\]locale[/\\]lang[/\\]zh-CN/,
        'element-ui/lib/locale/lang/ru-RU',
      ]);
  },

```

2. Component code

```
          <li :class="$style.menuItem">
            <div :class="[$style.icon, $style.menuIcon]">
              <img
                svg-inline
                src="./img/profile.svg"
              >
            </div>
            <div :class="$style.name">
              <span>{{ userNameShort }}</span>
            </div>
          </li>

```

No errors, but doest not inline it

**Comment by alex-shamshurin** [comment]
![image](https://user-images.githubusercontent.com/1595209/61314758-ffb70c80-a805-11e9-8b64-7337fe4ec341.png)

**Comment by oliverfindl** [comment]
Hello,

I see you are using [vue-cli](https://github.com/vuejs/vue-cli) in your project. So I tested my [vue-cli example](https://github.com/oliverfindl/vue-svg-inline-loader/tree/master/examples/vue-cli) and it works for me. I also tried with options provided and works too (btw. if you are using `strict: false`, you don't have to use `svg-inline` directive).

Can you provide a dummy repo, where would be this issue reproducible? Eventually, try to check out my [vue-cli example](https://github.com/oliverfindl/vue-svg-inline-loader/tree/master/examples/vue-cli) mentioned above, if you have issue there too.

Thanks

**Comment by alex-shamshurin** [comment]
Strict - it was an attempt to solve this. In my case it doesn't transform. Maybe it has some 'debug' option?

**Comment by oliverfindl** [comment]
Hello,

there isn't debug mode available, although it should throw errors if there are any.

You can try to check path to svg file, if it's correct. It would be better, if you can use `@` [alias](https://webpack.js.org/configuration/resolve/) to `src` folder, instead of relative paths. But anyways, as mentioned above, it should [throw an error](https://github.com/oliverfindl/vue-svg-inline-loader/blob/c37f10cc989582d47c4a6ee8955db7de309cdcb9/src/index.js#L187) if file is not found.

You can also try to manually [inspect](https://cli.vuejs.org/guide/webpack.html#inspecting-the-project-s-webpack-config) generated webpack config and check for any errors/misconfiguration there.

I'm afraid I can't assist you further without a dummy repo, where I could reproduce and debug this issue.
Please create a minimal repo with [vue-cli](https://github.com/vuejs/vue-cli) (or you can use my [vue-cli example](https://github.com/oliverfindl/vue-svg-inline-loader/tree/master/examples/vue-cli) as reference), where you are encountering this issue.

Thanks

**Comment by alex-shamshurin** [comment]
Magic: commented out 

```
config
      .plugin('NormalModuleReplacementPlugin')
      .use(webpack.NormalModuleReplacementPlugin, [
        /element-ui[/\\]lib[/\\]locale[/\\]lang[/\\]zh-CN/,
        'element-ui/lib/locale/lang/ru-RU',
      ]);

```

and it works. Then I removed comments again - still works. So it seems to be like a webpack cache issue.

**Comment by oliverfindl** [comment]
I'm glad, you figured it out!
