### ISSUE TITLE
How to use with laravel-mix

### ISSUE THREAD

**Issue by Darkecudoua** [oliverfindl/vue-svg-inline-loader#23]
This is not a direct issue but I struggle configuring this with laravel mix. I implemented this in the frontend, on Vue2, and I used the basic webpack config file. In the meantime, the dev team implemented the backend on Laravel along with Laravel-mix. Since then, vue-svg-inline-loader has stopped working. I think the culprit is the misconfiguration, as with laravel mix I do not have the **"vue.config.js"** file anymore, but I have **"webpack.mix.js"**.

I tried this:
```
mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.vue$/,
                use: [
                    {
                        loader: "vue-loader",
                        options: { /* ... */ }
                    },
                    {
                        loader: "vue-svg-inline-loader",
                        options: { /* ... */ }
                    }
                ]
            },
        ]
    },
});
```

and

```
mix.webpackConfig({
    module : {
        rules : [
            {
                use : [
                    'vue-svg-inline-loader',
                    {
                        loader: 'vue-svg-inline-loader',
                        options : {}
                    },
                ]
            },
        ]
    },
});
```

What am I missing?

Thank you

**Comment by oliverfindl** [comment]
Hello,

Unfortunately, I'm not familiar with [Laravel Mix](https://github.com/JeffreyWay/laravel-mix), so I can't assist you with your issue. But few days ago, somebody else had [issue](https://github.com/oliverfindl/vue-svg-inline-loader/issues/22) with [Laravel Mix](https://github.com/JeffreyWay/laravel-mix). Maybe it's related, or it's some recent change in [Laravel Mix](https://github.com/JeffreyWay/laravel-mix), because there wasn't any reported issues so far.

Maybe try to ask in [Laravel Mix](https://github.com/JeffreyWay/laravel-mix) repo for solution, and let us know.

Thanks

**Comment by Darkecudoua** [comment]
Hey @oliverfindl, thanks for answering and for providing a lead. After a night of brainstorming I managed to make it work, to a degree.

This is how my webpack.mix.js looks like right now:

```
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .copy('resources/assets', 'public/assets', true)
    .webpackConfig({
        module: {
            rules: [
                {
                    use: [
                        {
                            loader: 'vue-svg-inline-loader',
                        }
                    ]
                }
            ]
        }
    });
```

The only problem right now is that it converts every .SVG, even the ones that I used as a `background-image` in CSS. When I was using this directly in vue it was behaving as expected, i.e. inlining only the imgs that had the svg-inline attribute on them.
I suppose I need some sort of rule? Or I misunderstood something?

**Comment by oliverfindl** [comment]
Hello,

you are missing definition, which files should this loader process. Add this before `use` key:
```
test: /\.vue$/,
use: [ /* ... */ ]
```

Let me know if it helps.

Thanks

**Comment by Darkecudoua** [comment]
When I add the test definition it does not compile anymore. This is how the code looks like
```
mix.js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .copy('resources/assets', 'public/assets', true)
    .webpackConfig({
        module: {
            rules: [
                {
                    test: /\.vue$/,
                    use: [
                        {
                            loader: "vue-svg-inline-loader",
                            options: {
                                    inline: {
                                        keyword: "svg-inline",
                                        strict: true
                                    }
                            }
                        }
                    ]
                }
            ]
        }
    });
```

and this is the error
```
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by oliverfindl** [comment]
Hello,

your last config seems alright to me.

According [Laravel Mix API](https://github.com/JeffreyWay/laravel-mix/blob/master/setup/webpack.mix.js), method `mix.webpackConfig({})` is overriding webpack.config.js, so maybe it's required to define whole config, because it's not merging them together...
I found there another method `mix.override(function (webpackConfig) {})` which supplies actual webpack config, so you could fiddle with this method and debug it with `console.log(webpackConfig); process.exit();`. There is also method `mix.dump();` which seems to output webpack config to console, so you can also examine it this way.

I seen you also submitted [issue](https://github.com/JeffreyWay/laravel-mix/issues/2204) to [Laravel Mix](https://github.com/JeffreyWay/laravel-mix) repo, so I'm curious for their solution.

Please let me know, if you made some progress.

Thanks

**Comment by Darkecudoua** [comment]
Hello @oliverfindl ,

I received some help from the guys at Laravel Mix. The problem is now fixed. I believe you may add this snippet in the docs as they may be other users facing this (kind of) problem.

Here's the code:
```
mix.override(config => {
    config.module.rules.push({
        test: /\.vue$/,
        use: [{ loader: 'vue-svg-inline-loader' }]
    })
});
```

**Comment by oliverfindl** [comment]
Hello,

thanks for your contribution!

I updated [README.md](https://github.com/oliverfindl/vue-svg-inline-loader/blob/master/README.md) according configuration you provided. Hope it will help more people.

Thanks

**Comment by oliverfindl** [comment]
Closing this issue.
