### ISSUE TITLE
Using Deprecated Babel Libraries

### ISSUE THREAD

**Issue by jtsom** [oliverfindl/vue-svg-inline-loader#25]
Installing the latest version, npm shows that deprecated Babel libraries are being used:

```
-> % npm update
npm WARN deprecated @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
npm WARN deprecated package has been deprecated in favor of directly
npm WARN deprecated including core-js/stable (to polyfill ECMAScript
npm WARN deprecated features) and regenerator-runtime/runtime
npm WARN deprecated (needed to use transpiled generator functions):
npm WARN deprecated 
npm WARN deprecated   > import "core-js/stable";
npm WARN deprecated   > import "regenerator-runtime/runtime";
+ vue-svg-inline-loader@1.2.18
```

**Comment by oliverfindl** [comment]
Hello,

while this library became deprecated (which is non-breakable change), it still works as expected.

You can refer to my comment [here](https://github.com/oliverfindl/vue-svg-inline-loader/pull/18#issuecomment-506818097) for more info why I'm not going to fix this anytime soon. If you have some spare time, you can submit PR, that will be tested in all major versions of [Node.js](https://github.com/nodejs) since version 6.

Thanks

**Comment by oliverfindl** [comment]
Hello,

in version 2.0.0 was package @babel/polyfill removed. Should fix this issue.

Closing this issue as resolved.

Thanks.
