### ISSUE TITLE
v1.3.0 introduced some breaking changes regarding attribute usage

### ISSUE THREAD

**Issue by RenanOliv** [oliverfindl/vue-svg-inline-loader#32]
Prior to v1.3.0 you could use any atributes in the `<img>` tag declaration and these would be preserved during the `<svg>` transformation.  😢

Now all attributes are being removed in favor of the new `addAttributes` option. This is a problem if you've had different attributes values and properties per icon.

There is also another breaking change that class values are being transformed to lowercase, and since CSS is case-sensitive this break any icon that use a style name such as `class="fooBar"`.

**Comment by heydtn** [comment]
I ran into this yesterday as well, and had to specify a specific previous version.  This also causes issues with any sort of data bindings, too.  Although the attribute options are now removed, there's still vue directives which are actively affected. 

```
<img
  v-else-if="myProperty"
  svg-inline
  ...
>
```

```
[Vue warn] Property or method "myproperty" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
```

As a side note, I used both directives as well as attributes on almost every single SVG, most being camelCase so neither the lower casing nor the dropping of specific attributes are compatible.

**Comment by oliverfindl** [comment]
Hello,

thank you for reporting issues. Let me address them one by one.

---

> Prior to v1.3.0 you could use any attributes in the <img> tag declaration and these would be preserved during the <svg> transformation.

I tested this with my webpack and vue-cli example from [examples](https://github.com/oliverfindl/vue-svg-inline-loader/tree/master/examples) and its working for me. Can you provide some example where I can replicate your issue?

---

> Now all attributes are being removed in favor of the new addAttributes option. This is a problem if you've had different attributes values and properties per icon.

`addAttributes` option should not interfere with preservation of original attributes. Tested with same examples as above. So again, I will need some example where I can replicate your issue.

---

> There is also another breaking change that class values are being transformed to lowercase, and since CSS is case-sensitive this break any icon that use a style name such as class="fooBar".

Can confirm, will fix in next update (probably this weekend).

---
 
> I ran into this yesterday as well, and had to specify a specific previous version. ...

Vue directives were fixed in latest release ([1.3.3](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.3.3)).
I tested this behavior with `v-if` and `v-else-if` on examples mentioned above. Worked for me with no issues. If you still have this issue with latest release, please provide full example of your code.

---

Thanks

**Comment by oliverfindl** [comment]
Hello,

issue with lowercase-ing attribute values should be fixed now.

Please give me feedback if it works as expected

Thanks

**Comment by heydtn** [comment]
Of course =)  The issue with directives was related to the lowercasing of attributes. It was causing issues in 1.3.3, but it looks like this is remedied in 1.4.1, yay!

**Comment by oliverfindl** [comment]
Closing this issue.
