### ISSUE TITLE
can't work when using `lang=pug`

### ISSUE THREAD

**Issue by psephopaiktes** [oliverfindl/vue-svg-inline-loader#36]
Hello fellow developers, this is so lovely plugin for me.

I want to use in `<temaplte lang="pug">` and `img(svg-inline class="icon" src="@/assets/logo-default.svg" alt="alt")`, but it's not work.

Thanks.

**Comment by oliverfindl** [comment]
Hello,

unfortunately, this is true. Pug syntax is not supported. As stated in [README.md](https://github.com/oliverfindl/vue-svg-inline-loader/blob/master/README.md), this loader works only with HTML syntax, because it's using regular expressions to match and replace parts of source code.

If you have any more questions, feel free to ask.

Thanks

**Comment by psephopaiktes** [comment]
Understand.
I'll write directly like `<img>` in pug. (It works)

Thank you so much.
