### ISSUE TITLE
@click.native and @click.stop is not working

### ISSUE THREAD

**Issue by DineshSrisrimal** [oliverfindl/vue-svg-inline-loader#38]
@click.native is not working and thus @click.native.stop is also not working.

**Comment by oliverfindl** [comment]
Hello,

Can confirm this issue. It's caused by `.` (dot) character in attribute name ([Vue](https://github.com/vuejs/vue) event modifier).

I updated loader and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.4.5](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.4.5).

Please give me feedback if it works as expected.

Thanks

**Comment by DineshSrisrimal** [comment]
Hey, @oliverfindl Thanks for your quick response. I am using the version ^1.2.12 and that might be the issue. I did a hotfix by adding event.stopPropogation(). I will check and let you know.

**Comment by DineshSrisrimal** [comment]
@click.stop works @oliverfindl Thanks for the quick update.
