### ISSUE TITLE
Loading SVG from Alias Path not working

### ISSUE THREAD

**Issue by kaipaysen** [oliverfindl/vue-svg-inline-loader#4]
Hi there,

I just ran into this issue: while loading SVGs from relative paths "just works", it doesn't when using an alias path. This is my webpack config:

```
module: {
        rules: [
// ..                
            {
                test: /\.vue$/,
                use: [
                    'vue-loader', {
                    loader: "vue-svg-inline-loader",
                    options: {}
                }]
            },
        ]
    },
```

```
resolve: {
// ...
        alias: {
// ...
            "resources":    path.resolve(__dirname, "src/resources"),
// ...
        }
    },
```

And in one VUE single file component I'm using the following two. The latter is not working.
```
<img svg-inline class="icon" src="../../../resources/icons/baseline-equalizer-24px.svg" alt="example" />
<img svg-inline class="icon" src="~resources/icons/baseline-equalizer-24px.svg" alt="example" />
```

**Comment by oliverfindl** [comment]
Hello,

you are missing ~ (tilde) in your alias definition.
Im using similar alias and it works without any problems.
```json
"@": resolve(__dirname, "src")
```

Let me know if it solves your issue.

Thanks

**Comment by kaipaysen** [comment]
Hello,

tried that giving me a file not found error like that:
```WARNING in ./src/components/views/pulse-rate/pulse-rate-view.vue
Module build failed (from ./node_modules/vue-svg-inline-loader/dist/index.min.js):
Error: File /resources/icons/baseline-3d_rotation-24px.svg does not exist.
```

Thank you very much for looking into that.
Kai

**Comment by oliverfindl** [comment]
Hello,

I cannot simulate your error, although I just tested this myself, and it works for me only if alias key is the `"@"` as I posted before. Any other configuration seems not to work for me, even I copied the exact row and changed only alias key...

In network tab you can see, that its still requesting your alias key instead of alias value.
Anyhow, this is issue/feature not related to this loader, but [webpack](https://webpack.js.org/configuration/resolve/#resolve-alias) itself. Loader does not have any functionality related to webpack aliases.

So workaroud would be use only the `"@"` key, that works (atleas for me). If you manage to find better solution, please let me know. The `"@"` key also could be some kind of magic, that vue-loader does.

One more tip: don't use ~ (tilde) as your alias key, because in unix systems is ~/ used as location for users home.

Thanks

**Comment by kaipaysen** [comment]
Hi There,

> URLs prefixed with ~ are treated as a module request, similar to require('some-module/image.png'). You need to use this prefix if you want to leverage Webpack's module resolving configurations. For example if you have a resolve alias for assets, you need to use <img src="~assets/logo.png"> to ensure that alias is respected.

I've been checking the source code and it might be related to [this line](https://github.com/oliverfindl/vue-svg-inline-loader/blob/d04e45b3ad2dae3e92026f5568df3f69dacc4429/src/index.js#L141).
I think it might be worth to use the webpack resolve function similar to this:
```
		this.resolve(this.context, source, function(err, resolvedPath) {
			if (!err) 
				console.log(resolvedPath);
		})
```

How do you feel about it?

Cheers,
Kai

**Comment by kaipaysen** [comment]
more complete code:

```
		let fullPath = await new Promise((resolve, reject) => {
			this.resolve(this.context, source, function(err, resolvedPath) {
				if (err) reject(err);
				else resolve(resolvedPath);
			});
		});
		let file = { path: fullPath };
```

**Comment by tybruffy** [comment]
Just installed this loader and came here to post the same issue. Hoping this PR  gets merged in quickly!

**Comment by oliverfindl** [comment]
Hello guys,

I merged the PR #5 and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.1.4](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.1.4).

Thanks for your contribution to this loader.

**Comment by tybruffy** [comment]
Working flawlessly for me now. 👍

**Comment by oliverfindl** [comment]
I'm glad it works.

Closing this issue.

**Comment by mesqueeb** [comment]
I cannot seem to get my relative path work... This is my config:

```js
extendWebpack (cfg) {
  cfg.module.rules.push({
    enforce: 'pre',
    test: /\.(js|vue)$/,
    loader: 'eslint-loader',
    exclude: /node_modules/
  })
  cfg.module.rules.push({
    test: /\.vue$/,
    use: [
      {
        loader: 'vue-svg-inline-loader',
        options: { /* ... */ }
      }
    ]
  })
  cfg.resolve.alias = {
    ...cfg.resolve.alias, // This adds the existing aliases
    // Add your own alias like this:
    'styl/variables': path.resolve(__dirname, './src/css/themes/common.variables.styl'),
    '~svg': path.resolve(__dirname, './src/assets'),
  }
}
```

I'm trying to get the `~svg` to work. Any advice for me?

**Comment by oliverfindl** [comment]
Hello,

just tested your config in my [webpack example](https://github.com/oliverfindl/vue-svg-inline-loader/tree/master/examples/webpack) (defined in [webpack.config.js](https://github.com/oliverfindl/vue-svg-inline-loader/blob/master/examples/webpack/webpack.config.js)) and it's working fine for me.
Also tried [vue-cli example](https://github.com/oliverfindl/vue-svg-inline-loader/tree/master/examples/vue-cli) and it worked too. For some reason `config.resolve.alias` in vue-cli is treated like `Map` and not like `Object`.

```javascript
cfg.resolve.alias.set("~svg", path.resolve(__dirname, "./src/assets"));
```

I'm not familiar, how you use webpack in your project. Maybe your problem is in `module.rules` part of config:

```javascript
cfg.module.rules.push({
    test: /\.vue$/,
    use: [ /* ... */ ]
})
```

Where you are pushing 2nd rule for `.vue` files and not changing the one, thats already there.

Thanks

**Comment by mesqueeb** [comment]
Hi! 
thanks so much for your advice.
Maybe I added the webpack loader wrongly.

I am using the quasar framework who has a short section on how to add webpack loaders here.
[Webpack-Loaders](https://quasar-framework.org/guide/app-pre-processors-and-webpack.html#Webpack-Loaders). But maybe I made a mistake adding it?

When I tried to also `use: [ {loader: 'vue-loader'}, ...` I got "rendered is undefined". Deleting the regular vue loader worked, since I think Quasar Framework adds one for me already.

**Comment by oliverfindl** [comment]
Hello,

unfortunately, I'm not familiar with Quasar or `extendWebpack`. But I checked the docs and it seems you can use `chainWebpack` too. This should be same as is in my [vue-cli example](https://github.com/oliverfindl/vue-svg-inline-loader/tree/master/examples/vue-cli) - [vue.config.js](https://github.com/oliverfindl/vue-svg-inline-loader/blob/master/examples/vue-cli/vue.config.js), which worked fine for me.

This should fix loader issue (if there is any). But you will have to read the [docs](https://github.com/neutrinojs/webpack-chain) to setup rest of your actual webpack config.

Thanks
