### ISSUE TITLE
Attribute collision when one is bound and the other is not (using : shortand and not v-bind)

### ISSUE THREAD

**Issue by oliverpool** [oliverfindl/vue-svg-inline-loader#41]
I upgraded my dependencies and I have some issues with the latest version (1.4.6).
By testing the older releases, it appears that the bug got introduced on version 1.3.0 (1.2.18 works fine).

My code:
```
      <img
        svg-inline
        src="../../assets/icon.svg"
        class="fill-current menu-icon"
        :class="{ 'text-red-900': !active }"
      />
```

Expected output: `<svg>` tag with at least the static classes (`fill-current menu-icon`)

Instead I get: the static part is removed, only the `:class` part is respected (` `)

Interestingly, if I make a trivial modification to the class (add a whitespace for instance), the hot-reload injects the updated static classes and everything looks fine again.

---

**Furthermore, if I replace `:class` with `v-bind:class`**
- on v1.3.0,  everything seems to be fine
- on v1.4.6 the compilation fails with `duplicate attribute: v-bind:class`

Probably relevant commit: https://github.com/oliverfindl/vue-svg-inline-loader/commit/f5f0a0ff1b44f5de9381f70c991089892901ef99 (#28)

**Comment by oliverpool** [comment]
Removing the following lines fixes my issue. https://github.com/oliverfindl/vue-svg-inline-loader/blob/8b854b761a4b79f114690072b2b8418878d4fce8/src/index.js#L288-L291 

I am not sure what is their purpose.

**Comment by oliverpool** [comment]
I have been reading the code and I think that it could be a cool idea to implement this "attribute merging" as a [`svgo` plugin](https://github.com/svg/svgo/blob/master/docs/how-it-works/en.md).

If you think that this idea is worth a try, I may be able find some spare time next week !

**Comment by oliverfindl** [comment]
Hello,

I tested this case with your `<img />` tag (and as a bonus, I added class `icon` right into `<svg />` file) and this is what output from this loader looks like:
```xml
<svg
	xmlns="http://www.w3.org/2000/svg"
	viewBox="..."
 	class="icon"
	v-bind:svg-inline="''"
	v-bind:class="'fill-current menu-icon'"
	:class="{ 'text-red-900': !active }"
	v-bind:role="'presentation'"
	v-bind:focusable="'false'"
	v-bind:tabindex="'-1'"
>
	<!-- ... -->
</svg>
```

As you can see in this output, class is defined with `class`, `:class` and `v-bind:class`.
- `class` is static class from `<svg />` file
- `:class` is reactive class from your `<img />` tag
- `v-bind:class` is static class from your `<img />` tag converted to [Vue](https://github.com/vuejs/vue) v-bind directive

Reason behind using `v-bind` directive was, that [Vue](https://github.com/vuejs/vue) alone will handle merging or replacing attributes (not only class attribute, but all attributes) according its own logic. I wanted to avoid situations, that would result in different behavior in [Vue](https://github.com/vuejs/vue) and this loader.

This change was introduced, because handling of same attribute on `<img />` tag and `<svg />` file was not implemented at all. So I thought this will be simpliest solution for this issue.

But as we see now, I wasn't right... But still, I got feeling, that when I developed this feature, it was working. So maybe something in [Vue](https://github.com/vuejs/vue) was changed in meantime, but I'm not sure about this.

I already have logic for handling attributes in place in my [vue-svg-inline-plugin](https://github.com/oliverfindl/vue-svg-inline-plugin), but I don't want to use it here (unless neccessary), if [Vue](https://github.com/vuejs/vue) can somehow handle it by itself. If you check the code, it's pretty lengthy implementation.

I will try to think about the best solution for this issue, but I'm not sure about outcome. As workaround you can use your `:class` on parent element and style it as a child of this parent. I know, it's not convenient, but it should do the trick.

Thanks

**Comment by oliverpool** [comment]
> I will try to think about the best solution for this issue, but I'm not sure about outcome. As workaround you can use your :class on parent element and style it as a child of this parent. I know, it's not convenient, but it should do the trick.

An easier workaround (without change to my CSS) is to manually merge my static `class` inside my bounded `:class`:
```
:class="{ 'text-red-900': !active, 'fill-current menu-icon': true }"
```

**Comment by oliverfindl** [comment]
Hello,

that's will do to trick too!

I was thinking a bit about merging logic, and I want to track all possible attribute names and values that can appear in code.

Attribute name:
- `attribute-name` - static
- `:attribute-name` - reactive (shorthand)
- `v-bind:attribute-name` - reactive

Attribute value (static):
-  (empty, e.g.: `attribute-name=""`)
- `single-value`
- `single-value single-value ...` (multiple values)

Attribute value (reactive):
- `'static-value'`
- `variable`
- `computedProp`
- `method()`
- `method(param0, param1, ...)`
- `'static-part-' + reactivePart`
- ``` `static-part-${reactivePart}` ```
- `{ 'class-name-0': variableOrComputedPropOrMethod, 'class-name-1':  !!variable, ... }`
- ```[ variable0 ? 'class-name-0' : ('class-name-' + variable1), !variable1 ? `class-name-${variable2}` : '', ... ]```
- and as bonus, all single quotes can be replaced with double quotes

For static attributes it would be simple - just replace them (or join them together with space in case of style attribute), or in case of class attribute - split both values by whitespace, merge them together, filter unique and join them back with space. Tricky part is, to define order of processing. Should be first processed attribute from `<svg />` tag and then potentially overwritten by logic (e.g.: style or class order) of attribute from `<img />`  file? Or vice-versa?

Reactive part gets tricky even more. In fact, you can have reactive attributes defined in `<svg />` file (although, it's not advertised anywhere for obvious reasons) and [Vue](https://github.com/vuejs/vue) would handle it's logic. Attribute name can be normalized to same form (by extending shorthand to `v-bind:` or `v-on:`), but reactive part could not be easily merged, if at all.

I will keep thinking about this more, but more I think, more I'm sure it will end up in complete rewrite of this plugin...

Thanks

**Comment by oliverpool** [comment]
After thinking about this as well, I see two other possible solutions:

**_Simple solution_** (restore compatibility at the cost of removing the "feature" of #28)

Remove the "faulty" lines https://github.com/oliverfindl/vue-svg-inline-loader/blob/8b854b761a4b79f114690072b2b8418878d4fce8/src/index.js#L288-L291

In case of #28, the user should write the workaround himself (`:class="'...'"` instead of `class="..."` inside the vue component).
This change would restore the compatibility (which has been been broken with the 1.3.0 update), at the cost of having to manually svg files having a `class` (I don't think this case was supported by this library before 1.3.1).

**_Complete solution_** (support both cases, requires a deeper rewriting)

Write a custom svgo plugin, to benefit from the parsing of svg and alter the attributes during svgo optimization (instead of relying on brittle regexes).

**Comment by oliverfindl** [comment]
Hello,

your simple solution would cause breaking changes for users, that count on this behavior. That would require releasing updated version as next major version (@v2.x.x) doesn't feel right for me...

Some time ago I was thinking about using proper HTML / XML / DOM parser, but at that time, I didn't find single one, that was maintained and could return back modified DOM as string. That could solve both - template (or whole component) and SVG file parsing without regexes.

As hotfix, I could create new option, that would disable this feature if desired. 

I will look into this hotfix later today or this week.

Thanks

**Comment by oliverfindl** [comment]
Hello,

I updated loader and published it to [npm](https://www.npmjs.com/package/vue-svg-inline-loader). Current version is [1.5.0](https://github.com/oliverfindl/vue-svg-inline-loader/releases/tag/v1.5.0).

You can turn off transformation to `v-bind:` syntax with [transformImageAttributesToVueDirectives](https://github.com/oliverfindl/vue-svg-inline-loader#configuration) option.

Please give me feedback if it works as expected.

Thanks

**Comment by oliverpool** [comment]
Works perfectly

Thank you so much for the quick fix!
