### ISSUE TITLE
Overwriting the addAttributes option does not remove default attributes

### ISSUE THREAD

**Issue by heatherpekrul** [oliverfindl/vue-svg-inline-loader#48]
### Steps to reproduce:

Added the following to vue.config.js:
```
config.module
      .rule('vue')
      .use('vue-svg-inline-loader')
      .loader('vue-svg-inline-loader')
      .options({
        addAttributes: {
          role: 'presentation',
        },
      });
```

Expected the resulting HTML to contain this:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" svg-inline="" role="presentation">`

Instead this was the resulting SVG element:
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" svg-inline="" role="presentation" focusable="false" tabindex="-1">`

The only way that I found to actually remove default attributes was to utilize `removeAttributes`. If I supply an alternative value for a default attribute, then the attribute's value is updated, but the only way to remove is via `removeAttributes`.

It is preferable for the default `addAttributes` options not to be added if an alternative object is supplied.

**Comment by oliverfindl** [comment]
Hello,

thanks for your issue, but this is by-design. This behavior is mentioned at [bottom of configuration section](https://github.com/oliverfindl/vue-svg-inline-loader#notices). As you mentioned, you should use `removeAttributes` option for this kind of situation. I believe, that for most users are this behavior expected and helpful.

Anyway, I got already working prototype of version 3 of this loader, which is complete rewrite, where all attribute-related logic would be completely in developers hands. Unfortunately, my time is limited, and its nowhere near being finished and therefore not ready for release in near future.

Closing this issue for now, because it is not an real issue, just an opinion. If you have more questions or ideas for next version, feel free to reply here.

Thanks.
