### ISSUE TITLE
Some SVG doesn't work others yes

### ISSUE THREAD

**Issue by giovannidias1** [oliverfindl/vue-svg-inline-loader#49]
I'm trying to add new icons but these don't work 
the old ones work normally

old  SVG 
```
<svg id="shopping-cart" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <path d="M24.17 26.86a4.03 4.03 0 1 1 4.03-4.02 4.03 4.03 0 0 1-4.03 4.02zm0-5.37a1.34 1.34 0 1 0 1.35 1.35 1.34 1.34 0 0 0-1.35-1.35zM12.09 26.86a4.03 4.03 0 1 1 4.03-4.02 4.03 4.03 0 0 1-4.03 4.02zm0-5.37a1.34 1.34 0 1 0 1.34 1.35 1.34 1.34 0 0 0-1.34-1.35z"/><path d="M9.4 4.03l.67 2.68H28.4l-2.57 9.4H10.45L6.93 2.05A2.68 2.68 0 0 0 4.33 0H1.33a1.34 1.34 0 0 0 0 2.69h2.98l3.52 14.08a2.69 2.69 0 0 0 2.6 2.03h15.4a2.69 2.69 0 0 0 2.58-1.98l3.5-12.8z"/>
</svg>
```

new SVG

```<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="22" height="22" viewBox="0 0 22 22"><defs><style>.a,.c{fill:none;}.a{stroke:#707070;}.b{clip-path:url(#a);}.c{stroke:#fff;stroke-linecap:round;stroke-linejoin:round;stroke-width:1.25px;}</style><clipPath id="a"><rect class="a" width="22" height="22" transform="translate(425 24)"/></clipPath></defs><g class="b" transform="translate(-425 -24)"><g transform="translate(425.75 25.06)"><path class="c" d="M5,15.937h8.267A1.25,1.25,0,0,0,14.5,14.9L16.7,1.98A1.25,1.25,0,0,1,17.93.94h.82"/><path class="c" d="M6.562,17.812a.312.312,0,1,1-.312.313.312.312,0,0,1,.312-.312"/><path class="c" d="M12.812,17.812a.312.312,0,1,1-.312.313.312.312,0,0,1,.312-.312"/><path class="c" d="M14.961,12.187H4.9a2.5,2.5,0,0,1-2.425-1.893L1.268,5.461a.625.625,0,0,1,.607-.777H16.237"/></g></g></svg>```

error in build 

```
ERROR in ./Assets/js/Components/Header/Menu/menuConversion.vue?vue&type=template&id=766d3104& (./node_modules/vue-loader/lib/loaders/templateLoader.js??vue-loader-options!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/vue-svg-inline-loader/src!./Assets/js/Components/Header/Menu/menuConversion.vue?vue&type=template&id=766d3104&)
Module Error (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
(Emitted value instead of an instance of Error) 

  Errors compiling template:

  Templates should only be responsible for mapping the state to the UI. Avoid placing tags with side-effects in your templates, such as <style>, as they will not be parsed.
```

**Comment by oliverfindl** [comment]
Hello,

in your case, it is not issue with this loader, but with your SVG which contains `style` tag. This is not allowed inside `template` tag in SFC. Exactly as stated in your error output.

If you have more questions, feel free to ask here.

Thanks.

**Comment by giovannidias1** [comment]
Why does it work when I use require()

dont work

`      <img svg-inline class="icon--shop" src="icon/win10/shopping-cart-2.svg">
`

works

      <img class="icon--shop" :src="require('icon/win10/shopping-cart-2.svg')">

**Comment by oliverfindl** [comment]
Hello,

as for `require` function, I can not tell. It is core function of [webpack](https://github.com/webpack/webpack) and it depends on your particular [webpack](https://github.com/webpack/webpack) config and used loaders. Most probably you will end up with base64-encoded image instead of inline SVG.

Issue with using attributes as `id`, `class` or `style` tag in SVG is with their scope. As for SVG editor, it is scoped by SVG file itself. But while using it with this loader, they will get inserted directly into your template and you might end up with duplicate ids, classes and styles which will override themself by latest used SVG. Therefore it is issue, besides of SFC which does not allow `style` tags inside `template` tag.

Hope this helps.

Thanks.

**Comment by oliverfindl** [comment]
Closing this issue.
